# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  NODE_VERSION: 14.5.0

jobs:
  test-app:
    name: Test app
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update npm
        run: npm i -g npm@7

      - name: Get npm cache path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      # - name: Cache npm cache and node_modules
      #   id: cache-dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ${{ steps.npm-cache-dir-path.outputs.dir }}
      #       node_modules
      #     key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

      # - name: Install dependencies
      #   run: npm ci
      #   if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test:ember

